### ISSUE TITLE
Bug - 

### ISSUE THREAD

**Issue by Sw0rdiX** [Sebastian-Fitzner/veams-components#4]
veams-components/veams-components/slide-fox/js/slide-fox.js line 47

`render() {
        Helpers.isInViewport(this.$el) ? this.showSlideFox() : this.hideSlideFox(); // this.$el should be this.el for getting offsetTop,...
 }`

swx

**Comment by andy-gutsche** [comment]
Fix version: v1.0.4

Original repository for component: https://github.com/Veams/veams-component-slide-fox
